#version of docker-compose
version: '3.9'

# services
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4444:80"
    volumes:
      - ./backend:/var/www/html/backend # live reload